### ISSUE TITLE
certificate_of_origin sourcecode?

### ISSUE THREAD

**Issue by drandreaskrueger** [energywebfoundation/bond#5]
# open source?

The second from the top on  
https://github.com/energywebfoundation/bond/tree/master/bond

says `certificate_of_origin @ 0c1a4b0` - so it is a submodule, right?

But clicking on the link results in

> 404 page not found.

https://github.com/energywebfoundation/certificate_of_origin  
https://github.com/energywebfoundation/certificate_of_origin/tree/0c1a4b077f5bc1d4aa483fb99dd2530a54b56f57

and 

```
git submodule update --init --recursive
```
results in 
```
Submodule 'certificate_of_origin' (git@github.com:energywebfoundation/certificate_of_origin.git) registered for path 'bond/certificate_of_origin'
Cloning into '~/Documents/Code/energywebfoundation_bond/bond/certificate_of_origin'...
```
```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
```
fatal: clone of 'git@github.com:energywebfoundation/certificate_of_origin.git' 
into submodule path
 '~/Documents/Code/energywebfoundation_bond/bond/certificate_of_origin' failed
```

I would like to look at that certificate_of_origin code.

Thanks a lot!

**Comment by christinto** [comment]
Has anyone been able to get in touch with the EWF Ramp-up team for the OS images? Seems like they've gone closed source.

**Comment by drandreaskrueger** [comment]
> the EWF Ramp-up team for the OS images?

I am trying all this with "Running on local environment", and not "Deploying on hardware".

So I don't need the OS image, right?

**Comment by drandreaskrueger** [comment]
> I would like to look at that certificate_of_origin code.

Ah, wow, is that it? -->

--> https://github.com/energywebfoundation/bond/tree/ricmm-work-multicon-resin/bond/certificate_of_origin

It was hidden in a branch ;-)


Is that all I need? How stable is that branch? 

Thanks!

**Comment by drandreaskrueger** [comment]
Will have time for this on Monday and Tuesday.

any hints? Thanks!

**Comment by christinto** [comment]
> So I don't need the OS image, right?

I'm not sure what happen if you are not "deploying on hardware". Are you just injecting in fake energy data to the smart contracts from your own custom oracle then?

**Comment by christinto** [comment]
> Is that all I need? How stable is that branch?

Would be nice to have someone from EW comment 👍

**Comment by drandreaskrueger** [comment]
> I'm not sure what happen if you are not ...

same here, also not sure. 

I am here in order to explore their stuff.

**Comment by christinto** [comment]
> I am here in order to explore their stuff.

Cool, yeah it would be interesting to see if we could push data via a raspberry pi or arduino to the same contract code?!

**Comment by cerealkill** [comment]
Available now [here](https://github.com/energywebfoundation/ew-origin/tree/master/contracts).
