### ISSUE TITLE
(test failing) carbonemission.py line 13 - read_state() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by drandreaskrueger** [energywebfoundation/bond#7]
```
python test.py

Test:  EnergyMeterTest
Case:  extended
.Test:  WattimeTest
Case:  extended
E
======================================================================
ERROR: extended (test.carbonemission.WattimeTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../energywebfoundation_bond/bond/test/carbonemission.py", line 16, in extended
    self.simple()
  File ".../energywebfoundation_bond/bond/test/carbonemission.py", line 13, in simple
    self.assertIsInstance(self.meter.read_state('National+Grid'), CarbonEmissionData)
TypeError: read_state() takes 1 positional argument but 2 were given

----------------------------------------------------------------------
Ran 2 tests in 1.003s

FAILED (errors=1)
```

before:

* is EnergyWebClient running? Yes
* EWC Version: Energy Web/v1.12.0-unstable-a7d13fb69-20180509/x86_64-linux-gnu/rustc1.25.0
* Bond Version: commit f35fb72ec394335cc83541a6a3a4286168635fcf cerealkill Configuring parity to ewf tobalaba chain
* is the virtualenv started? yes
* are all dependencies installed? Yes, all but the one (see other issue) `eth-tester`

**Comment by cerealkill** [comment]
Hi Andreas, first of all, thanks for being interest in this code and repository. I will fix the tests and requirements and will let you know via this issue.

**Comment by drandreaskrueger** [comment]
>  fix the tests and requirements   
> and will let you know via this issue.

thanks a lot !

**Comment by drandreaskrueger** [comment]
once all tests are going through, please also write a quickstart manual how to start the whole dapp. 

Is it as simple as `python bond.py`?

The README.md only talks about `python test.py`

Thanks a lot!

**Comment by cerealkill** [comment]
I am creating a better README, thanks for the feedback! About the tests, I removed then and ported the complexity and portability to the [bond library](https://github.com/energywebfoundation/ew-link-bond). This repository will remain for show case purposes only.
